name: PR Entrypoint

concurrency:
  group: pr-entrypoint-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        required: false

env:
  IS_CI: "yes"

jobs:
  build_docker_for_test:
    uses: ./.github/workflows/build_docker_for_test.yaml
    with:
      otp_vsn: "25.3.2-1"
      elixir_vsn: "1.14.5"
