name: build enterprise package

on:
  pull_request:
    branches:
      - 'enterprise'
      - 'dev/e/*'
  push:
    branches:
      - 'enterprise'
      - 'dev/e/*'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: node:16.20
    steps:
      - uses: actions/checkout@v2
      - name: install zip
        run: apt-get update && apt-get install -y zip
      - name: build
        run: |
          pnpm install
          pnpm build:enterprise
      - name: create package
        run: |
          touch dist/version
          echo "github_ref: $GITHUB_REF" >> dist/version
          echo "github_sha: $GITHUB_SHA" >> dist/version
          PACKAGE_NAME=$(echo ${GITHUB_REF##*/}) # Extract tag from GITHUB_REF
          zip -rq emqx-enterprise-dashboard-$PACKAGE_NAME.zip ./dist
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: emqx-enterprise-dashboard
          path: dist/
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: EMQX Dashboard ${{ github.ref }} Released
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./emqx-enterprise-dashboard-${{ env.PACKAGE_NAME }}.zip
          asset_name: emqx-enterprise-dashboard-${{ env.PACKAGE_NAME }}.zip
          asset_content_type: application/zip
