name: Sync to enterprise

on:
  push:
    branches:
      - dev/*

jobs:
  sync_to_enterprise:
    runs-on: ubuntu-20.04
    if: github.repository == 'emqx/emqx-dashboard5'
    steps:
      - name: create pull request
        id: create_pull_request
        run: |
          set -euo pipefail
          EE_REF="enterprise"
          echo "echo"
          R=$(curl --silent --show-error \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.CI_GIT_TOKEN }}" \
            -X POST \
            -d "{\"title\": \"Sync code from $GITHUB_REF to $EE_REF\", \"head\": \"$GITHUB_REF\", \"base\":\"$EE_REF\"}" \
            https://api.github.com/repos/${{ github.repository_owner }}/emqx-dashboard5/pulls)

